# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-06-30 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20230629_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='lessons/materials'),
        ),
    ]
